name: MyEconomy
version: 1.1.0
main: net.brcdev.myeconomy.MyEconomyPlugin
author: brc
softdepend: [ShopGUIPlus]
api-version: 1.8
commands:
  sp:
    description: "MyEconomy main command"
    usage: "/sp"
  spadd:
    description: "MyEconomy main"
    usage: "/spadd"