name: MyEconomy
version: 1.1.0
main: net.brcdev.myeconomy.MyEconomyPlugin
author: brc
softdepend: [ShopGUIPlus]
api-version: 1.13
commands:
  myeconomy:
    description: "MyEconomy main command"
    usage: "/myeconomy"